### ISSUE TITLE
Fan always on after running biddibi_boddibi_boo.sh

### ISSUE THREAD

**Issue by jeremyj563** [rbonghi/jetson_easy#1]
Is this intentional? How can we restore the factory setting for the fan so that it doesn't run unless needed?

**Comment by rbonghi** [comment]
Hi @jeremyj563 
The fan is on because the jetson_clock working, If you want switch of you can disable the service with:
1. Temporary disable: `sudo service jetson_performance stop`
2. Disable service: `sudo systemctl disable jetson_performance.service`

Other information are written here: https://github.com/rbonghi/jetson_easy/wiki/jetson_performance

I hope I help you, if you have other issues don't hesitate to write me :-)

**Comment by jeremyj563** [comment]
Excellent. Thank you!
