### ISSUE TITLE
Unable to deselect options

### ISSUE THREAD

**Issue by nfopma** [rbonghi/jetson_easy#4]
![setup jetson_easy](https://user-images.githubusercontent.com/14862977/40054409-0bad23e2-5845-11e8-99f9-ea5030e1fdd6.png) 

Unfortunately I am unable to deselect options in this menu.

**Comment by nfopma** [comment]
@gavanderhoorn

**Comment by rbonghi** [comment]
Hi @nfopma, to select/deselect an option you can use the arrows to move in each module, press **enter** and when you read the "Enable or disable this module" press enter otherwise if you see directly a menu look like this:
![run_script](https://user-images.githubusercontent.com/4551246/40098677-b4031c72-5917-11e8-80a4-c0aec8c266c9.png)
move the arrow on down and press **space** in the label "NO" and _after_ press **enter** to go back of the menu

I hope, I help you. If you have other questions don't esitate to write me.

**Comment by rbonghi** [comment]
Added in first menu the legend.
I hope now is more clear to move inside all menus.
![image](https://user-images.githubusercontent.com/4551246/40759229-14923bda-64cc-11e8-961d-129f632e3a4a.png)
