### ISSUE TITLE
Support for ROS melodic

### ISSUE THREAD

**Issue by teamimx** [rbonghi/jetson_easy#7]
Hey there

First of all, nice idea - a script like that is badly needed for the Jetson family of boards.

I gave it a spin today and have noticed that on Ubuntu 18.04 (artful) only Kinetic is presented as a viable option...do you have a timeframe when ROS melodic will be integrated? Also, even though Kinetic is available as an option, it does not install anything.

cheers,
michael

**Comment by rbonghi** [comment]
Hi @teamimx , thank you!

> I gave it a spin today and have noticed that on Ubuntu 18.04 (artful) only Kinetic is presented as a viable option...do you have a timeframe when ROS melodic will be integrated?

About ROS Melodic, I'm waiting the new release of the Jetpack for Jetson with Ubuntu 18.04 otherwise doesn't make more sense list Melodic when is impossible install on it :-)

> Also, even though Kinetic is available as an option, it does not install anything.

I check last time the installation in two step of ROS and works. (Run first time jetson_easy without install ROS, second step install ROS via jetson_easy) I will check again from scratch if the system works fine, I keep you posted on this issue ;-)

Best,
Raffaello
